trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: azurepipelinescanaryk8s

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    containerRegistry: 'ACRVOLARIS'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile
    tags: |
      $(Build.BuildId)
      latest
        
