trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: azure-pipelines-canary-k8s

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACRVOLARIS'
    repository: 'nodemonitor'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'